### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by gumeniukcom** [ferrix/suunendo#1]
I can't run you app:

vigo@vigo-work ~/suunto2end/suunendo $ ./suunendo.py Move_2013_11_08_08_13_31.xlsx 
from: can't read /var/mail/glob
from: can't read /var/mail/lxml
from: can't read /var/mail/dateutil
from: can't read /var/mail/datetime
from: can't read /var/mail/xlrd
./suunendo.py: line 12: syntax error near unexpected token `('
./suunendo.py: line 12:`timezone = pytz.timezone('EET')'

**Comment by ferrix** [comment]
Did you install pytz?

**Comment by gumeniukcom** [comment]
vigo-work suunto2end # pip freeze | grep pytz
Warning: cannot find svn location for distribute==0.6.24dev-r0
pytz==2013.8

**Comment by ferrix** [comment]
Apparently there is a new version of pytz. I can try and fix it sometime but if you install the old version or send a pull request for the new version, it will be faster. 

https://github.com/ferrix/suunendo/blob/master/requirements.txt

**Comment by gumeniukcom** [comment]
Downgrade:
vigo-work suunendo # pip freeze | grep pytz
Warning: cannot find svn location for distribute==0.6.24dev-r0
pytz==2010o

run:

vigo-work suunendo # ./suunendo.py Move_2013_11_08_08_13_31.xlsx 
from: can't read /var/mail/glob
from: can't read /var/mail/lxml
from: can't read /var/mail/dateutil
from: can't read /var/mail/datetime
from: can't read /var/mail/xlrd
./suunendo.py: line 12: syntax error near unexpected token `('
./suunendo.py: line 12:`timezone = pytz.timezone('EET')'

**Comment by OddBloke** [comment]
This might no longer be relevant, but this error shows up when you execute a Python script using a shell (instead of using Python itself).  Either use 'python ...' or add a shebang to the script.
